[project]
name = "variant-nnue-pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "chess>=1.11.2",
    "cupy-cuda11x>=13.6.0",
    "matplotlib>=3.10.7",
    "pytorch-lightning==1.9.5",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
]
